### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'target_volume'

### ISSUE THREAD

**Issue by LPY1219** [NVlabs/motion-policy-networks#16]
When I try to run    "python3 /root/mpinets/data_pipeline/gen_data.py dresser for-inference global 300 /root/data/inference/global/dresser_task.pkl"    for data generation,It gives the following errors:
  0%|                                                                                                                                   | 0/300 [11:37<?, ?it/s]
Traceback (most recent call last):
  File "/root/mpinets/data_pipeline/gen_data.py", line 1076, in <module>
    generate_inference_data(args.expert, args.how_many, args.save_path)
  File "/root/mpinets/data_pipeline/gen_data.py", line 948, in generate_inference_data
    generate_task_oriented_inference_data(expert_pipeline, how_many, save_path)
  File "/root/mpinets/data_pipeline/gen_data.py", line 848, in generate_task_oriented_inference_data
    obstacles=result.cuboids + result.cylinders,
TypeError: __init__() missing 1 required positional argument: 'target_volume'

I just follow the instructions in Readme.So I can not figure out why it gives such an error.

**Comment by vijayraj45** [comment]
Hi This is Vijay . While running the docker build (docker build --tag mpinets --network=host --file docker/Dockerfile .) Did you get any error in pointnet2_ops . For me it got stuck in Building wheels for pointnet2_ops (pyproject.toml) . How did you solve it.

**Comment by LPY1219** [comment]
> Hi This is Vijay . While running the docker build (docker build --tag mpinets --network=host --file docker/Dockerfile .) Did you get any error in pointnet2_ops . For me it got stuck in Building wheels for pointnet2_ops (pyproject.toml) . How did you solve it.

You can just go to the pointnet2_ops directory and command "pip install -e ."

**Comment by fishbotics** [comment]
@LPY1219 I believe this is a bug. Thanks for pointing it out. I'll have a fix tomorrow.

**Comment by LPY1219** [comment]
@fishbotics Could I ask whether you have sovled it out? I still have not figured out a solution

**Comment by fishbotics** [comment]
@LPY1219 : I created a branch that should fix the issue. Can you check out that branch and verify that it fixes the problem for you? Then I'll merge it in.

**Comment by LPY1219** [comment]
@fishbotics  Thanks for your reply,but it seems not work well.First,it gives the errors"[SyntaxError: non-default argument follows default argument]".I find that is because you define"negative_volumes: Obstacles = field(default_factory=lambda: [])" in Class Candidate.When other Classs（DresserCandidate，CubbyCandidate） inherits from it,some non-default argument will be defined.Therefore,the system gives the above error.Anyway,I have sovled it by define "negative_volumes: Obstacles = field(default_factory=lambda: [])"  in every single class rather than in base Candidate Class.Although the programm could run,the time is too long.It has been 8 hours since I start the command "python3 /root/mpinets/data_pipeline/gen_data.py dresser for-inference global 300 /root/data/inference/global/dresser_task.pkl" .And the program still dose not stop.I do not know whether it is still a bug or a normal phenomenon.

**Comment by LPY1219** [comment]
@fishbotics  Bad news!!   After more than 10 hours,the program gives the following errors:

19%|████████████████████████▎                                                                                                     | 58/300 [7:56:53<33:09:47, 493.34s/it]
Traceback (most recent call last):
  File "gen_data.py", line 1096, in <module>
    generate_inference_data(args.expert, args.how_many, args.save_path)
  File "gen_data.py", line 968, in generate_inference_data
    generate_task_oriented_inference_data(expert_pipeline, how_many, save_path)
  File "gen_data.py", line 821, in generate_task_oriented_inference_data
    env, all_results = gen_single_env_data()
  File "gen_data.py", line 648, in gen_single_env_data
    results = exhaust_environment(env, NUM_PLANS_PER_SCENE, selfcc)
  File "gen_data.py", line 563, in exhaust_environment
    results.extend(forward_backward(c1, c2, env.cuboids, env.cylinders, selfcc))
  File "gen_data.py", line 485, in forward_backward
    end_eff_plan, candidate1.config, cuboids, cylinders
  File "gen_data.py", line 301, in get_fabric_chunks
    matrix=kinematics.pose(joint_position, END_EFFECTOR_FRAME).matrix()
  File "/usr/local/lib/python3.7/dist-packages/geometrout/transform.py", line 126, in __init__
    self._so3 = SO3(Quaternion(matrix=matrix))
  File "/usr/local/lib/python3.7/dist-packages/pyquaternion/quaternion.py", line 101, in __init__
    self.q = Quaternion._from_matrix(kwargs["matrix"], **optional_args).q
  File "/usr/local/lib/python3.7/dist-packages/pyquaternion/quaternion.py", line 181, in _from_matrix
    raise ValueError("Matrix must be orthogonal, i.e. its transpose should be its inverse")
ValueError: Matrix must be orthogonal, i.e. its transpose should be its inverse

**Comment by fishbotics** [comment]
@LPY1219 , I updated that branch with a fix to that issue (and a few others that I ran into). I also fixed the default argument thing. I tested it on my end, but can you test it on yours? I suggest running this for a number smaller than 300 to start (I use 4 to verify things work).

**Comment by LPY1219** [comment]
@fishbotics   It works well on my end.Thanks!

**Comment by zichunxx** [comment]
Hi! @fishbotics 

> @fishbotics Bad news!! After more than 10 hours,the program gives the following errors:
> 
> 19%|████████████████████████▎ | 58/300 [7:56:53<33:09:47, 493.34s/it] Traceback (most recent call last): File "gen_data.py", line 1096, in generate_inference_data(args.expert, args.how_many, args.save_path) File "gen_data.py", line 968, in generate_inference_data generate_task_oriented_inference_data(expert_pipeline, how_many, save_path) File "gen_data.py", line 821, in generate_task_oriented_inference_data env, all_results = gen_single_env_data() File "gen_data.py", line 648, in gen_single_env_data results = exhaust_environment(env, NUM_PLANS_PER_SCENE, selfcc) File "gen_data.py", line 563, in exhaust_environment results.extend(forward_backward(c1, c2, env.cuboids, env.cylinders, selfcc)) File "gen_data.py", line 485, in forward_backward end_eff_plan, candidate1.config, cuboids, cylinders File "gen_data.py", line 301, in get_fabric_chunks matrix=kinematics.pose(joint_position, END_EFFECTOR_FRAME).matrix() File "/usr/local/lib/python3.7/dist-packages/geometrout/transform.py", line 126, in **init** self._so3 = SO3(Quaternion(matrix=matrix)) File "/usr/local/lib/python3.7/dist-packages/pyquaternion/quaternion.py", line 101, in **init** self.q = Quaternion._from_matrix(kwargs["matrix"], **optional_args).q File "/usr/local/lib/python3.7/dist-packages/pyquaternion/quaternion.py", line 181, in _from_matrix raise ValueError("Matrix must be orthogonal, i.e. its transpose should be its inverse") ValueError: Matrix must be orthogonal, i.e. its transpose should be its inverse

Seems like the above error still exists. 

This error is triggered by `python3 gen_data.py tabletop full-pipeline /root/data/tabletop/task_oriented/1/` with `NUM_SCENES = 200`. Here is the error report of mine:


```
pybullet build time: May 20 2022 19:43:01
Namespace(data_dir='/root/data/tabletop/task_oriented/1/', env_type='tabletop', fabric_urdf='/isaac-sim/exts/omni.isaac.motion_generation/motion_policy_configs/franka/lula_franka_gen.urdf', neutral=False, run_type='full-pipeline')
Final data with save to /root/data/tabletop/task_oriented/1/
Temporary data will save to /tmp/tmp_data_9a1a9af2-2081-4887-bb50-31aa730b239e/
Using args:
    (env_type: tabletop)
    (neutral: False)
  0%|                                                                                             | 0/200 [03:23<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/mpinets/mpinets/data_pipeline/gen_data.py", line 671, in gen_single_env
    env, results = gen_single_env_data()
  File "/root/mpinets/mpinets/data_pipeline/gen_data.py", line 653, in gen_single_env_data
    results = exhaust_environment(env, NUM_PLANS_PER_SCENE, selfcc)
  File "/root/mpinets/mpinets/data_pipeline/gen_data.py", line 568, in exhaust_environment
    results.extend(forward_backward(c1, c2, env.cuboids, env.cylinders, selfcc))
  File "/root/mpinets/mpinets/data_pipeline/gen_data.py", line 511, in forward_backward
    end_eff_plan, candidate2.config, cuboids, cylinders
  File "/root/mpinets/mpinets/data_pipeline/gen_data.py", line 306, in get_fabric_chunks
    final_pose_q = Quaternion(matrix=final_pose_matrix, atol=1e-5)
  File "/usr/local/lib/python3.7/dist-packages/pyquaternion/quaternion.py", line 101, in __init__
    self.q = Quaternion._from_matrix(kwargs["matrix"], **optional_args).q
  File "/usr/local/lib/python3.7/dist-packages/pyquaternion/quaternion.py", line 181, in _from_matrix
    raise ValueError("Matrix must be orthogonal, i.e. its transpose should be its inverse")
ValueError: Matrix must be orthogonal, i.e. its transpose should be its inverse
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/mpinets/mpinets/data_pipeline/gen_data.py", line 1131, in <module>
    gen()
  File "/root/mpinets/mpinets/data_pipeline/gen_data.py", line 716, in gen
    total=NUM_SCENES,
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
ValueError: Matrix must be orthogonal, i.e. its transpose should be its inverse
```
Hope you can check it out when you are free. Thanks!

**Comment by fishbotics** [comment]
You could drop the tolerance in that function:   
```
File "/root/mpinets/mpinets/data_pipeline/gen_data.py", line 306, in get_fabric_chunks
    final_pose_q = Quaternion(matrix=final_pose_matrix, atol=1e-5)
```
Instead of using `1e-5`, you could try `1e-4`, but the higher the tolerance, the less precise the rotations will be. This error comes up because of some numerical instability when moving rotational matrices over from C++ (which is where Fabrics is implemented, the source code of which is not publicly available) to Python.  

I think it's probably fine if the rotation is less precise because there is a final collision checking process that ensures that the entire trajectory is valid before writing it to disk.

The other option would be to just wrap this call in a try/catch and skip any trajectory where this failure happens.

**Comment by varad-more** [comment]
Hi @fishbotics I tried changing atol, but still I'm struggling with same error. Due you have any other quick fixes for this issue?
I'm facing this issue only in tabletop task oriented environment.

**Comment by fishbotics** [comment]
Can you post your stack trace with the error? That'll make it easier to debug.

**Comment by fishbotics** [comment]
@varad-more, I'm happy to help debug here if you want to use geometric fabric as the expert but if you're open to it, you could also try using the codebase of the follow up work ["Avoid Everything"](https://github.com/fishbotics/avoid-everything). That codebase is more recent and uses AIT* trajectories as the expert (although there is no dresser environment in that codebase).

**Comment by varad-more** [comment]
@fishbotics Thank you so much suggestion, I'll checkout Avoid Everything data generation.

 

> Can you post your stack trace with the error? That'll make it easier to debug.

Here is my stack trace:

```

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "gen_data.py", line 670, in gen_single_env
    env, results = gen_single_env_data()
  File "gen_data.py", line 652, in gen_single_env_data
    results = exhaust_environment(env, NUM_PLANS_PER_SCENE, selfcc)
  File "gen_data.py", line 564, in exhaust_environment
    results.extend(forward_backward(c1, c2, env.cuboids, env.cylinders, selfcc))
  File "gen_data.py", line 510, in forward_backward
    end_eff_plan, candidate2.config, cuboids, cylinders
  File "gen_data.py", line 305, in get_fabric_chunks
    final_pose_q = Quaternion(matrix=final_pose_matrix, atol=1e-4)
  File "/usr/local/lib/python3.7/dist-packages/pyquaternion/quaternion.py", line 101, in __init__
    self.q = Quaternion._from_matrix(kwargs["matrix"], **optional_args).q
  File "/usr/local/lib/python3.7/dist-packages/pyquaternion/quaternion.py", line 181, in _from_matrix
    raise ValueError("Matrix must be orthogonal, i.e. its transpose should be its inverse")
ValueError: Matrix must be orthogonal, i.e. its transpose should be its inverse
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gen_data.py", line 1127, in <module>
    gen()
  File "gen_data.py", line 715, in gen
    total=NUM_SCENES,
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
ValueError: Matrix must be orthogonal, i.e. its transpose should be its inverse
```
